### ISSUE TITLE
position (for an approximate progress bar)

### ISSUE THREAD

**Issue by tpapp** [bicycle1885/CodecZlib.jl#23]
I am reading and processing a large gzip-compressed file and want to show some progress information, preferably with [ProgressMeter.jl](https://github.com/timholy/ProgressMeter.jl), which has the following idiom:

```julia
seekend(io)
fileSize = position(io)
seekstart(io)
p = Progress(fileSize, 1)   # minimum update interval: 1 second
while !eof(io)
    line = readline(io)
    # Here's where you do all the hard, slow work
    
    update!(p, position(io))
end
```

In the example above, `io` would come from a `GzipDecompressorStream`. But 
```julia
julia> position(io)
ERROR: MethodError: no method matching position(::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor,IOStream})
```
I understand that the position may not be clearly defined because of buffering, but since `seekend` and `seekstart` are supported, is it possible to get eg the position of the original stream?

**Comment by nhz2** [comment]
`seekend` is not supported anymore, but `position` should work now. You can also use the [`TranscodingStreams.stats`](https://juliaio.github.io/TranscodingStreams.jl/stable/reference/#TranscodingStreams.stats) function to see how many bytes have been read from the original stream.
