### ISSUE TITLE
I got warning when using CSV package

### ISSUE THREAD

**Issue by tkosaka1976** [bicycle1885/CodecZlib.jl#28]
I got this warning:
Warning: Package CodecZlib does not have Libdl in its dependencies:

Please consider to update the code for CSV package.

**Comment by bicycle1885** [comment]
I think this is the same issue as https://discourse.julialang.org/t/updating-package-to-0-7-and-issue-with-libdl/12071/6, which should have been fixed by #26 (not yet released, but will happen very soon).

**Comment by tkosaka1976** [comment]
Thank you for your inform this.
I'll wait for the release.
