### ISSUE TITLE
Is it possible to use CodecZlib to read a csv?

### ISSUE THREAD

**Issue by endrebak** [bicycle1885/CodecZlib.jl#32]
https://stackoverflow.com/q/52590792/992687

Just wondering :)

**Comment by bicycle1885** [comment]
`CSV.read` seems to require `TranscodingStream` to implement the `position` function. There is already a feature request (https://github.com/bicycle1885/TranscodingStreams.jl/issues/62). I'd like to work on it soon but I cannot promise when.

**Comment by bjarthur** [comment]
+1 for fixing this.  it's breaking [RDatasets](https://github.com/johnmyleswhite/RDatasets.jl/issues/61), which is breaking [Gadfly](https://github.com/GiovineItalia/Gadfly.jl/pull/1201#issuecomment-426268326) tests.  let me know if i can help.

**Comment by nhz2** [comment]
Yes, this is possible. Ref: https://github.com/JuliaData/CSV.jl/pull/864
