### ISSUE TITLE
llvm-devel packages required for building

### ISSUE THREAD

**Issue by ksteimel** [bicycle1885/CodecZlib.jl#33]
Sorry to bother you. I was trying to install this package and found that I needed to install the development libraries for llvm (this was on fedora 28). Should this be mentioned somewhere in the documentation?

**Comment by bicycle1885** [comment]
Which Julia distribution did you use? I always use generic Linux binaries or macOS binaries distributed at https://julialang.org/downloads/ and I've never seen that requirement.

**Comment by ksteimel** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  ah that's probably it. I was using the julia version provided in the fedora repos. My apologies.                                                                                                                                                                           From: notifications@github.comSent: October 9, 2018 8:28 PMTo: CodecZlib.jl@noreply.github.comReply-to: reply@reply.github.comCc: ksteimel@iu.edu; author@noreply.github.comSubject: Re: [bicycle1885/CodecZlib.jl] llvm-devel packages required for building (#33)  Which Julia distribution did you use? I always use generic Linux binaries or macOS binaries and I've never seen that requirement.

**Comment by KristofferC** [comment]
Best is to use the official version since that is what everything gets tested with.
