### ISSUE TITLE
CRC call

### ISSUE THREAD

**Issue by bhalonen** [bicycle1885/CodecZlib.jl#35]
Would this be a good package to implement the crc calls to zlib?

**Comment by bicycle1885** [comment]
This package does not provide a function to calculate CRC32, but it's almost trivial to implement that using `ccall` and `CodecZlib.libz`.

**Comment by valeriuo** [comment]
I had a similar need and found the solution in [Libz.jl](https://github.com/BioJulia/Libz.jl/blob/master/src/checksums.jl).
On the other hand, although these days I mostly write C code, I tend to disagree with the use of `ccall`. I don't think the community wants to see Julia become the new Numba.

**Comment by nhz2** [comment]
https://github.com/JuliaIO/CRC32.jl is the package for this.
