### ISSUE TITLE
Find end of Zlib stream

### ISSUE THREAD

**Issue by simonbyrne** [bicycle1885/CodecZlib.jl#4]
I'm trying to read git packfiles, which contain chunks of Zlib-compressed data, so I want to do something like:
```
f = open(packfile)
nobjs = readheader(f)
for i = 1:nobjs
     nbytes = readchunkheader(f) # number of bytes in _decompressed_ data
     data = read(ZlibDecompressionStream(f), nbytes)
     # do something with `data`
end
```
However the problem is that `ZlibDecompressionStream` will buffer past the end of the relevant end of the data in `f` (so the position in the second loop will be in the wrong place). Is it possible to set the position of `f` back to the end of the zlib data?

**Comment by simonbyrne** [comment]
Or as a more concrete example:
```
using CodecZlib

text = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sollicitudin
mauris non nisi consectetur, a dapibus urna pretium. Vestibulum non posuere
erat. Donec luctus a turpis eget aliquet. Cras tristique iaculis ex, eu
malesuada sem interdum sed. Vestibulum ante ipsum primis in faucibus orci luctus
et ultrices posuere cubilia Curae; Etiam volutpat, risus nec gravida ultricies,
erat ex bibendum ipsum, sed varius ipsum ipsum vitae dui.
"""

data = transcode(ZlibCompression(), text)
s = IOBuffer(vcat(data,data)) # concatenate two zlib-compressed streams
zs = ZlibDecompressionStream(s)

read(zs, sizeof(text))
```
Is it possible to get `position(s)` to be `length(data)`?

**Comment by bicycle1885** [comment]
I think it is a little bit tricky to implement that since TranscodingStreams.jl does not know the end position of the zlib stream. I added *unread* methods (https://github.com/bicycle1885/TranscodingStreams.jl/pull/13), which inserts data into a stream. So, the code may look like:
```julia
f = NoopStream(open(packfile))
nobjs = readheader(f)
for i = 1:nobjs
     nbytes = readchunkheader(f) # number of bytes in _decompressed_ data
     s = ZlibDecompressionStream(f)
     data = read(s, nbytes)
     buffer = s.state.buffer2
     TranscodingStreams.unsafe_unread(f,
        TranscodingStreams.bufferptr(buffer),
        TranscodingStreams.buffersize(buffer))
     # do something with `data`
end
```

This code touches the internal fields and methods and so I need to prepare some nice interfaces to do that.
