### ISSUE TITLE
Are all 3 compressors in this package literally identical?

### ISSUE THREAD

**Issue by oxinabox** [bicycle1885/CodecZlib.jl#44]
The names seem synomous to me,
and the code for each looks identical.
Am I missing something?

**Comment by bicycle1885** [comment]
Each compressor has a different range of the`windowbits` parameter that is passed to zlib. Adding a magic number to the parameter or flipping the sign of it creates a different kind of compressor, but I think it is much clearer to allocate different names (types) to different compressors.
