### ISSUE TITLE
How to write valid empty gzip file?

### ISSUE THREAD

**Issue by blaiseli** [bicycle1885/CodecZlib.jl#47]
How should one proceed to generate a valid empty gzip file using CodecZlib?

Here is what I tried:

```
import CodecZlib
gz = CodecZlib
fh = gz.GzipCompressorStream(open("test_out.gz", "w"))
close(fh)
```

However, the following results in an empty file (zero bytes) that `gzip` cannot handle properly:

```
$ zcat test_out.gz 

gzip: test_out.gz: unexpected end of file
$
```

I can generate valid gzipped file using Python:

```
>>> from gzip import open as gzopen
>>> with gzopen("test_out.gz", "w") as fh:
...     pass
... 
```

The resulting file is not really empty (a few bytes), and `gzip` does not complain when I try to zcat it:

```
$ zcat test_out.gz
$
```

**Comment by nhz2** [comment]
To create an empty gzip file, you can use `TranscodingStreams.TOKEN_END`.

```julia
import TranscodingStreams
import CodecZlib
fh = CodecZlib.GzipCompressorStream(open("test_out.gz", "w"))
write(fh, TranscodingStreams.TOKEN_END)
close(fh)
```

Ideally, this would be simpler.
