### ISSUE TITLE
Build error in Ubuntu 20.04

### ISSUE THREAD

**Issue by sam81** [bicycle1885/CodecZlib.jl#54]
trying to load the `RDatasets` package I get the following error: `CodecZlib.jl is not installed properly, run Pkg.build("CodecZlib") and restart Julia`. However, when I run `Pkg.build("CodecZlib")` I get:

       Building CodecZlib → `~/.julia/packages/CodecZlib/5t9zO/deps/build.log`
    ┌ Error: Error building `CodecZlib`: 
    │ ERROR: LoadError: LibraryProduct(nothing, ["libz"], :libz, "Prefix(/home/sam/.julia/packages/CodecZlib/5t9zO/deps/usr)") is not satisfied, cannot generate deps.jl!
    │ Stacktrace:
    │  [1] error(::String) at ./error.jl:33
    │  [2] write_deps_file(::String, ::Array{LibraryProduct,1}; verbose::Bool, isolate::Bool) at /home/sam/.julia/packages/BinaryProvider/GeAtj/src/Products.jl:419
    │  [3] top-level scope at /home/sam/.julia/packages/CodecZlib/5t9zO/deps/build.jl:93
    │  [4] include(::String) at ./client.jl:439
    │  [5] top-level scope at none:5
    │ in expression starting at /home/sam/.julia/packages/CodecZlib/5t9zO/deps/build.jl:78
    └ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:892

This happens on Ubuntu 20.04 with Julia version:

    versioninfo()
    Julia Version 1.4.1
    Commit 381693d3df* (2020-04-14 17:20 UTC)
    Platform Info:
      OS: Linux (x86_64-pc-linux-gnu)
      CPU: Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
      WORD_SIZE: 64
      LIBM: libopenlibm
      LLVM: libLLVM-8.0.1 (ORCJIT, ivybridge)
    Environment:
      JULIA_NUM_THREADS = 8

**Comment by bicycle1885** [comment]
I cannot reproduce the problem with Julia 1.4.1 on Ubuntu 20.04. Can you reproduce it even after removing the `~/.julia` directory and then installing RDatasets.jl?

**Comment by sam81** [comment]
thanks the issue is gone after removing the old `~/.julia` directory and reinstalling `RDatasets`, sorry for the noise. I'm closing the bug. I'll keep the old `~/.julia` directory for a little while (I've just renamed, not deleted it) in case it should be useful for further investigations.
