### ISSUE TITLE
Possible to use pigz internally vs. zlib?

### ISSUE THREAD

**Issue by quinnj** [bicycle1885/CodecZlib.jl#63]
pigz is meant as a [multithreaded, drop-in replacement](https://zlib.net/pigz/) for zlib; could we add a depdendency on pigz_jll and switch to using it internally for CodecZlib.jl?

**Comment by odow** [comment]
This came up here: https://discourse.julialang.org/t/parallel-bzip2-ang-gzip-pbzip2-and-pigz/87096

**Comment by quinnj** [comment]
Ok, found https://github.com/JuliaIO/CodecZlib.jl/issues/53 which already discussed this. I think I may try doing a jll for the cloudflare zlib fork and maybe do a fork of this package with the zlib swapped and see what perf looks like.

(also pigz does not have library support, so that answers my original question here around whether we could use it)

**Comment by gbaraldi** [comment]
If someone wants to implement parallel zlib on julia you are welcome, it's quite likely it will be the fastest thing out there since the python one is already really fast.
