### ISSUE TITLE
error when running example from README

### ISSUE THREAD

**Issue by alexriss** [bicycle1885/CodecZlib.jl#67]
The example from the `README`, ```compressed = transcode(GzipCompressor, "test string")```, gives the following error:

```
MethodError: transcode(::Type{GzipCompressor}, ::String) is ambiguous. Candidates:
  transcode(T, src::String) in Base at c.jl:306
  transcode(::Type{C}, args...) where C<:TranscodingStreams.Codec in TranscodingStreams at ...\.julia\packages\TranscodingStreams\5yQuA\src\transcode.jl:33
Possible fix, define
  transcode(::Type{C}, ::String) where C<:TranscodingStreams.Codec
```

This seems to be a new issue with the recently released version of TranscodingStreams (v0.9.12).

**Comment by ViralBShah** [comment]
Not seeing this error any more. Please reopen with more details on Julia and package versions if still failing.
