### ISSUE TITLE
IOStream API completeness

### ISSUE THREAD

**Issue by alyst** [bicycle1885/CodecZlib.jl#7]
Would it be possible to add the other `IOStream` API methods, e.g. `position()`, `seek()/seekstart()/seekend()` to a generic `TranscodingStream`?

**Comment by alyst** [comment]
Sorry, I've just realized that I should have opened the issue in `TranscodingStreams.jl`.
Anyway, my case is that for `RData.jl` I'm currently using `GZip.jl`. I wanted to switch to `CodecZlib`, but the format checking routine uses `seekstart()`, which isn't available for `GzipDecompressionStream`.

**Comment by bicycle1885** [comment]
In general, it is impossible to implement `position` and `seek*` methods to the transcoding stream. However, it may be possible to achieve your goal without implementing these methods. For example, `TranscodingStreams.unread` *unreads* data, which makes it possible to implement the peek operation. I'd like to know what you really want to do exactly.

**Comment by alyst** [comment]
So here's more details.

`.rdata` is a gzipped binary format. It's supported by `RData.jl` and the format is registered in `FileIO`. `FileIO.detect_rdata()` uses `seekstart(io)` to go to the beginning of `io` (the decompressed stream) and check for the proper header.
Currently it's a common pattern for `FileIO.detectXXX()` routines to do `seekstart()` first. `seekstart()` is present in `GZip`, but not in `CodecZlib`, that's why my idea of converting `RData.jl` from `GZip` to the more recent `CodecZlib` didn't work out.
Also, since `FileIO.detectXXX(io)` doesn't initialize the stream, it cannot use `mark!()`/`reset()`.

OTOH, there's `RDatasets.jl` package (it's outdated, there's johnmyleswhite/RDatasets.jl#48 PR to fix it), which provides few hundred common benchmark datasets. Some of these data are provided as `.rdata` files (so the package depends on `RData.jl`), the rest are gzipped `.csv` (requires `CSV.jl` dependency).
When reading `.csv` tables, `CSV.jl` uses `nb_available(io)` call, which is present in `CodecZlib`, but not in `GZip`.

So currently `RDatasets.jl` have to depend both on `GZip` and `CodecZlib` to decompress gzipped files, which is not ideal.

**Comment by bicycle1885** [comment]
Okay, thinking more carefully, `Base.seekstart` and `Base.seekend` would be not so hard, `Base.position` will take a little bit of time, and `Base.seek` is not achievable in O(1). I've made a pull request (https://github.com/bicycle1885/TranscodingStreams.jl/pull/28) to implement `Base.seekstart` and `Base.seekend` to transcoding streams. Is it sufficient for you to finish your change?

**Comment by ltf-canada** [comment]
I have exactly the same problem with reading gzip files and trying to implement recovery. In my case I am reading line by line with readline. In certain situations, I need to save a recovery position and read ahead. If what I am looking for isn't found or is incomplete, I need to revert to the saved position.

At present, I am using Libz directly which has the same problem. I would like to switch to CodecZlib going forward.

**Comment by bicycle1885** [comment]
@ltf-canada I think what you want is `mark` and `reset`, which is already implemented in TranscodingStreams.j (https://github.com/bicycle1885/TranscodingStreams.jl/blob/2bc177c28e9d25853d3f912ec2e1dc94a62fa1ab/src/stream.jl#L190-L208).

**Comment by bicycle1885** [comment]
Close this issue since most APIs are implemented in TranscodingStreams.jl 0.4. Feel free to open a dedicated issue if you're not satisfied.

**Comment by tbenst** [comment]
couldn't seek be implemented like so?

```julia
function seek(s::TranscodingStreams.TranscodingStream, pos::Int) 
         seekstart(s)
         read(s, pos)
         s
end
```
